### ISSUE TITLE
Support for type variables in constructor arguments

### ISSUE THREAD

**Issue by srid** [obsidiansystems/aeson-gadt-th#11]
For this definition (the `-> b` argument in the Q constructor triggers the error):

```haskell
data Q a :: * -> * where
  Q :: a -> b -> Q a b

deriveJSONGADT ''Q
```

I get:

```
error:
    Exception when trying to run
compile-time code:
      substVarsWith: couldn't
look up variable substitution
for b_6989586621679488156
```

Using e40c293901a9cb9be4b0748109f4bc6806bfdb79

<details>
<summary>Real-world type</summary>
<code lang="haskell"><pre>data Graph' v :: (* -> *) -> * where
  Graph' :: AdjacencyMap v -> Map v (DMap vp Identity) -> Graph' v vp
</code></pre>
</details>

**Comment by cgibbard** [comment]
Can you write the instance you'd want it to produce by hand?

**Comment by cgibbard** [comment]
Note that it tries to derive an instance of FromJSON (Some (Q a)). That's sort of the point of this thing, to write the JSON instances for GADTs where you can determine the last type argument from the constructor (i.e. it's a type index rather than a type parameter).

Your type isn't a GADT (even though it's written using GADT syntax), so you could just use ordinary Generic or the TH that's in aeson to write the instances.

**Comment by srid** [comment]
Ah, okay. I had to _make_ it a GADT-looking-thing hoping the library would handle it. :-P So this is outside the scope of this library. I simplified the types as much as possible and came up with [a different question](https://stackoverflow.com/questions/55416906) to ask.
